[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
pci-info = "0.2.1" 
sysinfo = "0.33.1"
axum = "0.8.1"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
ping-rs = "0.1.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"